<?
$aMenuLinks = Array(
	Array(
		"Карьера", 
		"careers/", 
		Array(), 
		Array("menu_ico"=>"bi-arrow-right-circle"), 
		"" 
	),
	Array(
		"Преимущества", 
		"benefits/", 
		Array(), 
		Array("menu_ico"=>"bi-arrow-right-circle"), 
		"" 
	),
	Array(
		"Вакансии", 
		"vacancies/", 
		Array(), 
		Array("menu_ico"=>"bi-arrow-right-circle"), 
		"" 
	)
);
?>